<?php

namespace BangNokia\Pekyll\Providers;

class ViewServiceProvider extends \Illuminate\View\ViewServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->bind('view', function ($app) {
            $resolver = $app['view.engine.resolver'];
            $finder = $app['view.finder'];
            $factory = new \BangNokia\Pekyll\Factory($resolver, $finder, $app['events']);
            $factory->setContainer($app);
            $factory->share('app', $app);
            return $factory;
        });
    }

    public function boot()
    {
    }
}
