<?php

namespace BangNokia\Pekyll\Providers;

class ViewServiceProvider extends \Illuminate\View\ViewServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
    }
}
